Capitals = {'tirane': 'albania', 'algiers': 'algeria', 'andorra la vella': 'andorra', 'luanda': 'angola',
 'saint johns': 'antigua and barbuda', 'buenos aires': 'argentina', 'yerevan': 'armenia',
 'canberra': 'australia', 'vienna': 'austria', 'baku': 'azerbaijan', 'nassau': 'bahamas',
 'manama': 'bahrain', 'dhaka': 'bangladesh', 'bridgetown': 'barbados', 'minsk': 'belarus',
 'brussels': 'belgium', 'belmopan': 'belize', 'porto novo': 'benin', 'thimphu': 'bhutan',
 'la paz': 'bolivia', 'sarajevo': 'bosnia and herzegovina', 'gaborone': 'botswana',
 'brasilia': 'brazil', 'bandar seri begawan': 'brunei', 'sofia': 'bulgaria',
 'ouagadougou': 'burkina faso', 'gitega': 'burundi', 'phnom penh': 'cambodia', 'yaounde': 'cameroon',
 'ottawa': 'canada', 'praia': 'cape verde', 'bangui': 'central african republic', 'ndjamena': 'chad',
 'santiago': 'chile', 'beijing': 'china', 'bogota': 'colombia', 'moroni': 'comoros',
 'kinshasa': 'congo, democratic republic of the', 'brazzaville': 'congo, republic of the',
 'san jose': 'costa rica', 'yamoussoukro': 'côte d ivoire (ivory coast)', 'zagreb': 'croatia',
 'havana': 'cuba', 'nicosia': 'cyprus', 'prague': 'czech republic (czechia)',
 'copenhagen': 'denmark', 'djibouti': 'djibouti', 'roseau': 'dominica',
 'santo domingo': 'dominican republic', 'dili': 'east timor', 'quito': 'ecuador', 'cairo': 'egypt',
 'san salvador': 'el salvador', 'london': 'england', 'malabo': 'equatorial guinea',
 'asmara': 'eritrea', 'tallinn': 'estonia', 'mbabana': 'eswatini (swaziland)',
 'addis ababa': 'ethiopia', 'palikir': 'federated states of micronesia', 'suva': 'fiji',
 'helsinki': 'finland', 'paris': 'france', 'libreville': 'gabon', 'banjul': 'gambia',
 'tbilisi': 'georgia', 'berlin': 'germany', 'accra': 'ghana', 'athens': 'greece',
 'saint georges': 'grenada', 'guatemala': 'guatemala', 'conakry': 'guinea',
 'bissau': 'guinea-bissau', 'georgetown': 'guyana', 'port au prince': 'haiti',
 'tegucigalpa': 'honduras', 'budapest': 'hungary', 'reykjavik': 'iceland', 'new delhi': 'india',
 'jakarta': 'indonesia', 'tehran': 'iran', 'baghdad': 'iraq', 'dublin': 'ireland',
 'jerusalem': 'palastine', 'rome': 'italy', 'kingston': 'jamaica', 'tokyo': 'japan',
 'amman': 'jordan', 'nur sultan': 'kazakhstan', 'nairobi': 'kenya', 'tarawa atoll': 'kiribati',
 'pristina': 'kosovo', 'kuwait': 'kuwait', 'bishkek': 'kyrgyzstan', 'vientiane': 'laos',
 'riga': 'latvia', 'beirut': 'lebanon', 'maseru': 'lesotho', 'monrovia': 'liberia',
 'tripoli': 'libya', 'vaduz': 'liechtenstein', 'vilnius': 'lithuania', 'luxembourg': 'luxembourg',
 'antananarivo': 'madagascar', 'lilongwe': 'malawi', 'kuala lumpur': 'malaysia', 'male': 'maldives',
 'bamako': 'mali', 'valletta': 'malta', 'majuro': 'marshall islands', 'nouakchott': 'mauritania',
 'port louis': 'mauritius', 'mexico': 'mexico', 'chisinau': 'moldova', 'monaco': 'monaco',
 'ulaanbaatar': 'mongolia', 'podgorica': 'montenegro', 'rabat': 'morocco', 'maputo': 'mozambique',
 'nay pyi taw': 'myanmar (burma)', 'windhoek': 'namibia', 'kathmandu': 'nepal',
 'amsterdam': 'netherlands', 'wellington': 'new zealand', 'managua': 'nicaragua', 'niamey': 'niger',
 'abuja': 'nigeria', 'pyongyang': 'north korea', 'skopje': 'north macedonia (macedonia)',
 'belfast': 'northern ireland', 'oslo': 'norway', 'muscat': 'oman', 'islamabad': 'pakistan',
 'melekeok': 'palau', 'panama': 'panama', 'port moresby': 'papua new guinea', 'asuncion': 'paraguay',
 'lima': 'peru', 'manila': 'philippines', 'warsaw': 'poland', 'lisbon': 'portugal', 'doha': 'qatar',
 'bucharest': 'romania', 'moscow': 'russia', 'kigali': 'rwanda',
 'basseterre': 'saint kitts and nevis', 'castries': 'saint lucia',
 'kingstown': 'saint vincent and the grenadines', 'apia': 'samoa', 'san marino': 'san marino',
 'sao tome': 'sao tome and principe', 'riyadh': 'saudi arabia', 'edinburgh': 'scotland',
 'dakar': 'senegal', 'belgrade': 'serbia', 'victoria': 'seychelles', 'freetown': 'sierra leone',
 'singapore': 'singapore', 'bratislava': 'slovakia', 'ljubljana': 'slovenia',
 'honiara': 'solomon islands', 'mogadishu': 'somalia', 'seoul': 'south korea', 'juba': 'south sudan',
 'madrid': 'spain', 'pretoria': 'south africa', 'sri jayawardenapura kotte': 'sri lanka',
 'khartoum': 'sudan', 'paramaribo': 'suriname', 'stockholm': 'sweden', 'bern': 'switzerland',
 'damascus': 'syria', 'taipei': 'taiwan', 'dushanbe': 'tajikistan', 'dodoma': 'tanzania',
 'bangkok': 'thailand', 'lome': 'togo', 'nukualofa': 'tonga', 'tunis': 'tunisia',
 'ankara': 'türkiye (turkey)', 'ashgabat': 'turkmenistan', 'funafuti': 'tuvalu', 'kampala': 'uganda',
 'kyiv': 'ukraine', 'abu dhabi': 'united arab emirates', 'washington': 'united states',
 'montevideo': 'uruguay', 'tashkent': 'uzbekistan', 'port vila': 'vanuatu',
 'vatican': 'vatican city', 'caracas': 'venezuela', 'hanoi': 'vietnam', 'cardiff': 'wales',
 'sanaa': 'yemen', 'lusaka': 'zambia', 'harare': 'zimbabwe'}

print("===========================\nCAPITALS OF THE WORLD\n===========================")
User = input("Enter the Capital: ").lower()
while User in Capitals:
    print(f"You right , {User.capitalize()} is the capital of {Capitals[1]}")
    exit()
else:
    print(f'You are not right ,{User} not capital')